#!/usr/bin/env node
// quill-check — generated by quill-ds (scripts/build-check.mjs) from the token source
// and the role intents. Do not edit by hand: reinstall with
//   npx shadcn@latest add @quill/check --overwrite
// Usage: node scripts/quill-check.mjs [--dir <path>]… [--css <tailwind entry>] [--include-ui] [--json] [--quiet]
import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs'
import { join, relative, resolve, dirname, extname } from 'node:path'
import { createRequire } from 'node:module'

export const DATA = {
 "version": "0.13.0",
 "prefixes": [
  "bg",
  "text",
  "border",
  "ring",
  "outline",
  "fill",
  "stroke",
  "from",
  "to",
  "via",
  "decoration",
  "divide",
  "placeholder",
  "caret",
  "accent",
  "shadow",
  "font",
  "rounded",
  "leading",
  "tracking",
  "ease",
  "duration"
 ],
 "quillClasses": [
  "bg-background",
  "text-background",
  "border-background",
  "ring-background",
  "outline-background",
  "fill-background",
  "stroke-background",
  "from-background",
  "to-background",
  "via-background",
  "decoration-background",
  "divide-background",
  "placeholder-background",
  "caret-background",
  "accent-background",
  "shadow-background",
  "bg-foreground",
  "text-foreground",
  "border-foreground",
  "ring-foreground",
  "outline-foreground",
  "fill-foreground",
  "stroke-foreground",
  "from-foreground",
  "to-foreground",
  "via-foreground",
  "decoration-foreground",
  "divide-foreground",
  "placeholder-foreground",
  "caret-foreground",
  "accent-foreground",
  "shadow-foreground",
  "bg-card",
  "text-card",
  "border-card",
  "ring-card",
  "outline-card",
  "fill-card",
  "stroke-card",
  "from-card",
  "to-card",
  "via-card",
  "decoration-card",
  "divide-card",
  "placeholder-card",
  "caret-card",
  "accent-card",
  "shadow-card",
  "bg-card-foreground",
  "text-card-foreground",
  "border-card-foreground",
  "ring-card-foreground",
  "outline-card-foreground",
  "fill-card-foreground",
  "stroke-card-foreground",
  "from-card-foreground",
  "to-card-foreground",
  "via-card-foreground",
  "decoration-card-foreground",
  "divide-card-foreground",
  "placeholder-card-foreground",
  "caret-card-foreground",
  "accent-card-foreground",
  "shadow-card-foreground",
  "bg-popover",
  "text-popover",
  "border-popover",
  "ring-popover",
  "outline-popover",
  "fill-popover",
  "stroke-popover",
  "from-popover",
  "to-popover",
  "via-popover",
  "decoration-popover",
  "divide-popover",
  "placeholder-popover",
  "caret-popover",
  "accent-popover",
  "shadow-popover",
  "bg-popover-foreground",
  "text-popover-foreground",
  "border-popover-foreground",
  "ring-popover-foreground",
  "outline-popover-foreground",
  "fill-popover-foreground",
  "stroke-popover-foreground",
  "from-popover-foreground",
  "to-popover-foreground",
  "via-popover-foreground",
  "decoration-popover-foreground",
  "divide-popover-foreground",
  "placeholder-popover-foreground",
  "caret-popover-foreground",
  "accent-popover-foreground",
  "shadow-popover-foreground",
  "bg-primary",
  "text-primary",
  "border-primary",
  "ring-primary",
  "outline-primary",
  "fill-primary",
  "stroke-primary",
  "from-primary",
  "to-primary",
  "via-primary",
  "decoration-primary",
  "divide-primary",
  "placeholder-primary",
  "caret-primary",
  "accent-primary",
  "shadow-primary",
  "bg-primary-foreground",
  "text-primary-foreground",
  "border-primary-foreground",
  "ring-primary-foreground",
  "outline-primary-foreground",
  "fill-primary-foreground",
  "stroke-primary-foreground",
  "from-primary-foreground",
  "to-primary-foreground",
  "via-primary-foreground",
  "decoration-primary-foreground",
  "divide-primary-foreground",
  "placeholder-primary-foreground",
  "caret-primary-foreground",
  "accent-primary-foreground",
  "shadow-primary-foreground",
  "bg-secondary",
  "text-secondary",
  "border-secondary",
  "ring-secondary",
  "outline-secondary",
  "fill-secondary",
  "stroke-secondary",
  "from-secondary",
  "to-secondary",
  "via-secondary",
  "decoration-secondary",
  "divide-secondary",
  "placeholder-secondary",
  "caret-secondary",
  "accent-secondary",
  "shadow-secondary",
  "bg-secondary-foreground",
  "text-secondary-foreground",
  "border-secondary-foreground",
  "ring-secondary-foreground",
  "outline-secondary-foreground",
  "fill-secondary-foreground",
  "stroke-secondary-foreground",
  "from-secondary-foreground",
  "to-secondary-foreground",
  "via-secondary-foreground",
  "decoration-secondary-foreground",
  "divide-secondary-foreground",
  "placeholder-secondary-foreground",
  "caret-secondary-foreground",
  "accent-secondary-foreground",
  "shadow-secondary-foreground",
  "bg-muted",
  "text-muted",
  "border-muted",
  "ring-muted",
  "outline-muted",
  "fill-muted",
  "stroke-muted",
  "from-muted",
  "to-muted",
  "via-muted",
  "decoration-muted",
  "divide-muted",
  "placeholder-muted",
  "caret-muted",
  "accent-muted",
  "shadow-muted",
  "bg-muted-foreground",
  "text-muted-foreground",
  "border-muted-foreground",
  "ring-muted-foreground",
  "outline-muted-foreground",
  "fill-muted-foreground",
  "stroke-muted-foreground",
  "from-muted-foreground",
  "to-muted-foreground",
  "via-muted-foreground",
  "decoration-muted-foreground",
  "divide-muted-foreground",
  "placeholder-muted-foreground",
  "caret-muted-foreground",
  "accent-muted-foreground",
  "shadow-muted-foreground",
  "bg-accent",
  "text-accent",
  "border-accent",
  "ring-accent",
  "outline-accent",
  "fill-accent",
  "stroke-accent",
  "from-accent",
  "to-accent",
  "via-accent",
  "decoration-accent",
  "divide-accent",
  "placeholder-accent",
  "caret-accent",
  "accent-accent",
  "shadow-accent",
  "bg-accent-foreground",
  "text-accent-foreground",
  "border-accent-foreground",
  "ring-accent-foreground",
  "outline-accent-foreground",
  "fill-accent-foreground",
  "stroke-accent-foreground",
  "from-accent-foreground",
  "to-accent-foreground",
  "via-accent-foreground",
  "decoration-accent-foreground",
  "divide-accent-foreground",
  "placeholder-accent-foreground",
  "caret-accent-foreground",
  "accent-accent-foreground",
  "shadow-accent-foreground",
  "bg-destructive",
  "text-destructive",
  "border-destructive",
  "ring-destructive",
  "outline-destructive",
  "fill-destructive",
  "stroke-destructive",
  "from-destructive",
  "to-destructive",
  "via-destructive",
  "decoration-destructive",
  "divide-destructive",
  "placeholder-destructive",
  "caret-destructive",
  "accent-destructive",
  "shadow-destructive",
  "bg-border",
  "text-border",
  "border-border",
  "ring-border",
  "outline-border",
  "fill-border",
  "stroke-border",
  "from-border",
  "to-border",
  "via-border",
  "decoration-border",
  "divide-border",
  "placeholder-border",
  "caret-border",
  "accent-border",
  "shadow-border",
  "bg-input",
  "text-input",
  "border-input",
  "ring-input",
  "outline-input",
  "fill-input",
  "stroke-input",
  "from-input",
  "to-input",
  "via-input",
  "decoration-input",
  "divide-input",
  "placeholder-input",
  "caret-input",
  "accent-input",
  "shadow-input",
  "bg-ring",
  "text-ring",
  "border-ring",
  "ring-ring",
  "outline-ring",
  "fill-ring",
  "stroke-ring",
  "from-ring",
  "to-ring",
  "via-ring",
  "decoration-ring",
  "divide-ring",
  "placeholder-ring",
  "caret-ring",
  "accent-ring",
  "shadow-ring",
  "bg-chart-1",
  "text-chart-1",
  "border-chart-1",
  "ring-chart-1",
  "outline-chart-1",
  "fill-chart-1",
  "stroke-chart-1",
  "from-chart-1",
  "to-chart-1",
  "via-chart-1",
  "decoration-chart-1",
  "divide-chart-1",
  "placeholder-chart-1",
  "caret-chart-1",
  "accent-chart-1",
  "shadow-chart-1",
  "bg-chart-2",
  "text-chart-2",
  "border-chart-2",
  "ring-chart-2",
  "outline-chart-2",
  "fill-chart-2",
  "stroke-chart-2",
  "from-chart-2",
  "to-chart-2",
  "via-chart-2",
  "decoration-chart-2",
  "divide-chart-2",
  "placeholder-chart-2",
  "caret-chart-2",
  "accent-chart-2",
  "shadow-chart-2",
  "bg-chart-3",
  "text-chart-3",
  "border-chart-3",
  "ring-chart-3",
  "outline-chart-3",
  "fill-chart-3",
  "stroke-chart-3",
  "from-chart-3",
  "to-chart-3",
  "via-chart-3",
  "decoration-chart-3",
  "divide-chart-3",
  "placeholder-chart-3",
  "caret-chart-3",
  "accent-chart-3",
  "shadow-chart-3",
  "bg-chart-4",
  "text-chart-4",
  "border-chart-4",
  "ring-chart-4",
  "outline-chart-4",
  "fill-chart-4",
  "stroke-chart-4",
  "from-chart-4",
  "to-chart-4",
  "via-chart-4",
  "decoration-chart-4",
  "divide-chart-4",
  "placeholder-chart-4",
  "caret-chart-4",
  "accent-chart-4",
  "shadow-chart-4",
  "bg-chart-5",
  "text-chart-5",
  "border-chart-5",
  "ring-chart-5",
  "outline-chart-5",
  "fill-chart-5",
  "stroke-chart-5",
  "from-chart-5",
  "to-chart-5",
  "via-chart-5",
  "decoration-chart-5",
  "divide-chart-5",
  "placeholder-chart-5",
  "caret-chart-5",
  "accent-chart-5",
  "shadow-chart-5",
  "bg-sidebar",
  "text-sidebar",
  "border-sidebar",
  "ring-sidebar",
  "outline-sidebar",
  "fill-sidebar",
  "stroke-sidebar",
  "from-sidebar",
  "to-sidebar",
  "via-sidebar",
  "decoration-sidebar",
  "divide-sidebar",
  "placeholder-sidebar",
  "caret-sidebar",
  "accent-sidebar",
  "shadow-sidebar",
  "bg-sidebar-foreground",
  "text-sidebar-foreground",
  "border-sidebar-foreground",
  "ring-sidebar-foreground",
  "outline-sidebar-foreground",
  "fill-sidebar-foreground",
  "stroke-sidebar-foreground",
  "from-sidebar-foreground",
  "to-sidebar-foreground",
  "via-sidebar-foreground",
  "decoration-sidebar-foreground",
  "divide-sidebar-foreground",
  "placeholder-sidebar-foreground",
  "caret-sidebar-foreground",
  "accent-sidebar-foreground",
  "shadow-sidebar-foreground",
  "bg-sidebar-primary",
  "text-sidebar-primary",
  "border-sidebar-primary",
  "ring-sidebar-primary",
  "outline-sidebar-primary",
  "fill-sidebar-primary",
  "stroke-sidebar-primary",
  "from-sidebar-primary",
  "to-sidebar-primary",
  "via-sidebar-primary",
  "decoration-sidebar-primary",
  "divide-sidebar-primary",
  "placeholder-sidebar-primary",
  "caret-sidebar-primary",
  "accent-sidebar-primary",
  "shadow-sidebar-primary",
  "bg-sidebar-primary-foreground",
  "text-sidebar-primary-foreground",
  "border-sidebar-primary-foreground",
  "ring-sidebar-primary-foreground",
  "outline-sidebar-primary-foreground",
  "fill-sidebar-primary-foreground",
  "stroke-sidebar-primary-foreground",
  "from-sidebar-primary-foreground",
  "to-sidebar-primary-foreground",
  "via-sidebar-primary-foreground",
  "decoration-sidebar-primary-foreground",
  "divide-sidebar-primary-foreground",
  "placeholder-sidebar-primary-foreground",
  "caret-sidebar-primary-foreground",
  "accent-sidebar-primary-foreground",
  "shadow-sidebar-primary-foreground",
  "bg-sidebar-accent",
  "text-sidebar-accent",
  "border-sidebar-accent",
  "ring-sidebar-accent",
  "outline-sidebar-accent",
  "fill-sidebar-accent",
  "stroke-sidebar-accent",
  "from-sidebar-accent",
  "to-sidebar-accent",
  "via-sidebar-accent",
  "decoration-sidebar-accent",
  "divide-sidebar-accent",
  "placeholder-sidebar-accent",
  "caret-sidebar-accent",
  "accent-sidebar-accent",
  "shadow-sidebar-accent",
  "bg-sidebar-accent-foreground",
  "text-sidebar-accent-foreground",
  "border-sidebar-accent-foreground",
  "ring-sidebar-accent-foreground",
  "outline-sidebar-accent-foreground",
  "fill-sidebar-accent-foreground",
  "stroke-sidebar-accent-foreground",
  "from-sidebar-accent-foreground",
  "to-sidebar-accent-foreground",
  "via-sidebar-accent-foreground",
  "decoration-sidebar-accent-foreground",
  "divide-sidebar-accent-foreground",
  "placeholder-sidebar-accent-foreground",
  "caret-sidebar-accent-foreground",
  "accent-sidebar-accent-foreground",
  "shadow-sidebar-accent-foreground",
  "bg-sidebar-border",
  "text-sidebar-border",
  "border-sidebar-border",
  "ring-sidebar-border",
  "outline-sidebar-border",
  "fill-sidebar-border",
  "stroke-sidebar-border",
  "from-sidebar-border",
  "to-sidebar-border",
  "via-sidebar-border",
  "decoration-sidebar-border",
  "divide-sidebar-border",
  "placeholder-sidebar-border",
  "caret-sidebar-border",
  "accent-sidebar-border",
  "shadow-sidebar-border",
  "bg-sidebar-ring",
  "text-sidebar-ring",
  "border-sidebar-ring",
  "ring-sidebar-ring",
  "outline-sidebar-ring",
  "fill-sidebar-ring",
  "stroke-sidebar-ring",
  "from-sidebar-ring",
  "to-sidebar-ring",
  "via-sidebar-ring",
  "decoration-sidebar-ring",
  "divide-sidebar-ring",
  "placeholder-sidebar-ring",
  "caret-sidebar-ring",
  "accent-sidebar-ring",
  "shadow-sidebar-ring",
  "bg-link",
  "text-link",
  "border-link",
  "ring-link",
  "outline-link",
  "fill-link",
  "stroke-link",
  "from-link",
  "to-link",
  "via-link",
  "decoration-link",
  "divide-link",
  "placeholder-link",
  "caret-link",
  "accent-link",
  "shadow-link",
  "bg-success",
  "text-success",
  "border-success",
  "ring-success",
  "outline-success",
  "fill-success",
  "stroke-success",
  "from-success",
  "to-success",
  "via-success",
  "decoration-success",
  "divide-success",
  "placeholder-success",
  "caret-success",
  "accent-success",
  "shadow-success",
  "bg-warning",
  "text-warning",
  "border-warning",
  "ring-warning",
  "outline-warning",
  "fill-warning",
  "stroke-warning",
  "from-warning",
  "to-warning",
  "via-warning",
  "decoration-warning",
  "divide-warning",
  "placeholder-warning",
  "caret-warning",
  "accent-warning",
  "shadow-warning",
  "bg-info",
  "text-info",
  "border-info",
  "ring-info",
  "outline-info",
  "fill-info",
  "stroke-info",
  "from-info",
  "to-info",
  "via-info",
  "decoration-info",
  "divide-info",
  "placeholder-info",
  "caret-info",
  "accent-info",
  "shadow-info",
  "bg-working",
  "text-working",
  "border-working",
  "ring-working",
  "outline-working",
  "fill-working",
  "stroke-working",
  "from-working",
  "to-working",
  "via-working",
  "decoration-working",
  "divide-working",
  "placeholder-working",
  "caret-working",
  "accent-working",
  "shadow-working",
  "bg-queued",
  "text-queued",
  "border-queued",
  "ring-queued",
  "outline-queued",
  "fill-queued",
  "stroke-queued",
  "from-queued",
  "to-queued",
  "via-queued",
  "decoration-queued",
  "divide-queued",
  "placeholder-queued",
  "caret-queued",
  "accent-queued",
  "shadow-queued",
  "bg-paper",
  "text-paper",
  "border-paper",
  "ring-paper",
  "outline-paper",
  "fill-paper",
  "stroke-paper",
  "from-paper",
  "to-paper",
  "via-paper",
  "decoration-paper",
  "divide-paper",
  "placeholder-paper",
  "caret-paper",
  "accent-paper",
  "shadow-paper",
  "bg-paper-warm",
  "text-paper-warm",
  "border-paper-warm",
  "ring-paper-warm",
  "outline-paper-warm",
  "fill-paper-warm",
  "stroke-paper-warm",
  "from-paper-warm",
  "to-paper-warm",
  "via-paper-warm",
  "decoration-paper-warm",
  "divide-paper-warm",
  "placeholder-paper-warm",
  "caret-paper-warm",
  "accent-paper-warm",
  "shadow-paper-warm",
  "bg-paper-deep",
  "text-paper-deep",
  "border-paper-deep",
  "ring-paper-deep",
  "outline-paper-deep",
  "fill-paper-deep",
  "stroke-paper-deep",
  "from-paper-deep",
  "to-paper-deep",
  "via-paper-deep",
  "decoration-paper-deep",
  "divide-paper-deep",
  "placeholder-paper-deep",
  "caret-paper-deep",
  "accent-paper-deep",
  "shadow-paper-deep",
  "bg-ink",
  "text-ink",
  "border-ink",
  "ring-ink",
  "outline-ink",
  "fill-ink",
  "stroke-ink",
  "from-ink",
  "to-ink",
  "via-ink",
  "decoration-ink",
  "divide-ink",
  "placeholder-ink",
  "caret-ink",
  "accent-ink",
  "shadow-ink",
  "bg-ink-soft",
  "text-ink-soft",
  "border-ink-soft",
  "ring-ink-soft",
  "outline-ink-soft",
  "fill-ink-soft",
  "stroke-ink-soft",
  "from-ink-soft",
  "to-ink-soft",
  "via-ink-soft",
  "decoration-ink-soft",
  "divide-ink-soft",
  "placeholder-ink-soft",
  "caret-ink-soft",
  "accent-ink-soft",
  "shadow-ink-soft",
  "bg-ink-muted",
  "text-ink-muted",
  "border-ink-muted",
  "ring-ink-muted",
  "outline-ink-muted",
  "fill-ink-muted",
  "stroke-ink-muted",
  "from-ink-muted",
  "to-ink-muted",
  "via-ink-muted",
  "decoration-ink-muted",
  "divide-ink-muted",
  "placeholder-ink-muted",
  "caret-ink-muted",
  "accent-ink-muted",
  "shadow-ink-muted",
  "bg-terracotta",
  "text-terracotta",
  "border-terracotta",
  "ring-terracotta",
  "outline-terracotta",
  "fill-terracotta",
  "stroke-terracotta",
  "from-terracotta",
  "to-terracotta",
  "via-terracotta",
  "decoration-terracotta",
  "divide-terracotta",
  "placeholder-terracotta",
  "caret-terracotta",
  "accent-terracotta",
  "shadow-terracotta",
  "bg-terracotta-deep",
  "text-terracotta-deep",
  "border-terracotta-deep",
  "ring-terracotta-deep",
  "outline-terracotta-deep",
  "fill-terracotta-deep",
  "stroke-terracotta-deep",
  "from-terracotta-deep",
  "to-terracotta-deep",
  "via-terracotta-deep",
  "decoration-terracotta-deep",
  "divide-terracotta-deep",
  "placeholder-terracotta-deep",
  "caret-terracotta-deep",
  "accent-terracotta-deep",
  "shadow-terracotta-deep",
  "bg-moss",
  "text-moss",
  "border-moss",
  "ring-moss",
  "outline-moss",
  "fill-moss",
  "stroke-moss",
  "from-moss",
  "to-moss",
  "via-moss",
  "decoration-moss",
  "divide-moss",
  "placeholder-moss",
  "caret-moss",
  "accent-moss",
  "shadow-moss",
  "bg-moss-deep",
  "text-moss-deep",
  "border-moss-deep",
  "ring-moss-deep",
  "outline-moss-deep",
  "fill-moss-deep",
  "stroke-moss-deep",
  "from-moss-deep",
  "to-moss-deep",
  "via-moss-deep",
  "decoration-moss-deep",
  "divide-moss-deep",
  "placeholder-moss-deep",
  "caret-moss-deep",
  "accent-moss-deep",
  "shadow-moss-deep",
  "bg-indigo",
  "text-indigo",
  "border-indigo",
  "ring-indigo",
  "outline-indigo",
  "fill-indigo",
  "stroke-indigo",
  "from-indigo",
  "to-indigo",
  "via-indigo",
  "decoration-indigo",
  "divide-indigo",
  "placeholder-indigo",
  "caret-indigo",
  "accent-indigo",
  "shadow-indigo",
  "bg-indigo-deep",
  "text-indigo-deep",
  "border-indigo-deep",
  "ring-indigo-deep",
  "outline-indigo-deep",
  "fill-indigo-deep",
  "stroke-indigo-deep",
  "from-indigo-deep",
  "to-indigo-deep",
  "via-indigo-deep",
  "decoration-indigo-deep",
  "divide-indigo-deep",
  "placeholder-indigo-deep",
  "caret-indigo-deep",
  "accent-indigo-deep",
  "shadow-indigo-deep",
  "bg-gold",
  "text-gold",
  "border-gold",
  "ring-gold",
  "outline-gold",
  "fill-gold",
  "stroke-gold",
  "from-gold",
  "to-gold",
  "via-gold",
  "decoration-gold",
  "divide-gold",
  "placeholder-gold",
  "caret-gold",
  "accent-gold",
  "shadow-gold",
  "bg-gold-deep",
  "text-gold-deep",
  "border-gold-deep",
  "ring-gold-deep",
  "outline-gold-deep",
  "fill-gold-deep",
  "stroke-gold-deep",
  "from-gold-deep",
  "to-gold-deep",
  "via-gold-deep",
  "decoration-gold-deep",
  "divide-gold-deep",
  "placeholder-gold-deep",
  "caret-gold-deep",
  "accent-gold-deep",
  "shadow-gold-deep",
  "bg-gold-text",
  "text-gold-text",
  "border-gold-text",
  "ring-gold-text",
  "outline-gold-text",
  "fill-gold-text",
  "stroke-gold-text",
  "from-gold-text",
  "to-gold-text",
  "via-gold-text",
  "decoration-gold-text",
  "divide-gold-text",
  "placeholder-gold-text",
  "caret-gold-text",
  "accent-gold-text",
  "shadow-gold-text",
  "bg-teal",
  "text-teal",
  "border-teal",
  "ring-teal",
  "outline-teal",
  "fill-teal",
  "stroke-teal",
  "from-teal",
  "to-teal",
  "via-teal",
  "decoration-teal",
  "divide-teal",
  "placeholder-teal",
  "caret-teal",
  "accent-teal",
  "shadow-teal",
  "bg-teal-deep",
  "text-teal-deep",
  "border-teal-deep",
  "ring-teal-deep",
  "outline-teal-deep",
  "fill-teal-deep",
  "stroke-teal-deep",
  "from-teal-deep",
  "to-teal-deep",
  "via-teal-deep",
  "decoration-teal-deep",
  "divide-teal-deep",
  "placeholder-teal-deep",
  "caret-teal-deep",
  "accent-teal-deep",
  "shadow-teal-deep",
  "bg-accent-pigment-text",
  "text-accent-pigment-text",
  "border-accent-pigment-text",
  "ring-accent-pigment-text",
  "outline-accent-pigment-text",
  "fill-accent-pigment-text",
  "stroke-accent-pigment-text",
  "from-accent-pigment-text",
  "to-accent-pigment-text",
  "via-accent-pigment-text",
  "decoration-accent-pigment-text",
  "divide-accent-pigment-text",
  "placeholder-accent-pigment-text",
  "caret-accent-pigment-text",
  "accent-accent-pigment-text",
  "shadow-accent-pigment-text",
  "font-sans",
  "font-display",
  "font-heading",
  "font-mono",
  "font-ui",
  "font-data",
  "text-2xs",
  "text-xs",
  "text-sm",
  "text-base",
  "text-lg",
  "text-xl",
  "text-2xl",
  "text-3xl",
  "text-4xl",
  "text-5xl",
  "rounded-xs",
  "rounded-sm",
  "rounded-md",
  "rounded-lg",
  "rounded-xl",
  "rounded-2xl",
  "rounded-3xl",
  "rounded-4xl",
  "shadow-2xs",
  "shadow-xs",
  "shadow-sm",
  "shadow-md",
  "shadow-lg",
  "shadow-xl",
  "shadow-2xl",
  "leading-display",
  "leading-heading",
  "leading-ui",
  "leading-reading",
  "tracking-display",
  "tracking-label",
  "tracking-eyebrow"
 ],
 "vars": {
  "--background": "background",
  "--foreground": "foreground",
  "--card": "card",
  "--card-foreground": "card-foreground",
  "--popover": "popover",
  "--popover-foreground": "popover-foreground",
  "--primary": "primary",
  "--primary-foreground": "primary-foreground",
  "--secondary": "secondary",
  "--secondary-foreground": "secondary-foreground",
  "--muted": "muted",
  "--muted-foreground": "muted-foreground",
  "--accent": "accent",
  "--accent-foreground": "accent-foreground",
  "--destructive": "destructive",
  "--border": "border",
  "--input": "input",
  "--ring": "ring",
  "--chart-1": "chart-1",
  "--chart-2": "chart-2",
  "--chart-3": "chart-3",
  "--chart-4": "chart-4",
  "--chart-5": "chart-5",
  "--sidebar": "sidebar",
  "--sidebar-foreground": "sidebar-foreground",
  "--sidebar-primary": "sidebar-primary",
  "--sidebar-primary-foreground": "sidebar-primary-foreground",
  "--sidebar-accent": "sidebar-accent",
  "--sidebar-accent-foreground": "sidebar-accent-foreground",
  "--sidebar-border": "sidebar-border",
  "--sidebar-ring": "sidebar-ring",
  "--link": "link",
  "--success": "success",
  "--warning": "warning",
  "--info": "info",
  "--working": "working",
  "--queued": "queued",
  "--paper": "paper",
  "--paper-warm": "paper-warm",
  "--paper-deep": "paper-deep",
  "--ink": "ink",
  "--ink-soft": "ink-soft",
  "--ink-muted": "ink-muted",
  "--terracotta": "terracotta",
  "--terracotta-deep": "terracotta-deep",
  "--moss": "moss",
  "--moss-deep": "moss-deep",
  "--indigo": "indigo",
  "--indigo-deep": "indigo-deep",
  "--gold": "gold",
  "--gold-deep": "gold-deep",
  "--gold-text": "gold-text",
  "--teal": "teal",
  "--teal-deep": "teal-deep",
  "--accent-pigment-text": "accent-pigment-text"
 },
 "tokens": {
  "text": {
   "2xs": 11.2,
   "xs": 12,
   "sm": 13.6,
   "base": 15.2,
   "lg": 18.4,
   "xl": 24,
   "2xl": 32,
   "3xl": 48,
   "4xl": 64,
   "5xl": 88
  },
  "radius": {
   "xs": 2,
   "sm": 4,
   "md": 6,
   "lg": 8,
   "xl": 16,
   "2xl": 24,
   "3xl": 32,
   "4xl": 40
  },
  "tracking": {
   "display": -0.03,
   "label": 0.1,
   "eyebrow": 0.15
  },
  "leading": {
   "display": 1.05,
   "heading": 1.2,
   "ui": 1.5,
   "reading": 1.7
  },
  "shadow": [
   "2xs",
   "xs",
   "sm",
   "md",
   "lg",
   "xl",
   "2xl"
  ],
  "motion": {
   "duration": {
    "--dur-fast": 200,
    "--dur": 300,
    "--dur-slow": 500
   },
   "ease": [
    "--ease-out",
    "--ease-soft"
   ]
  }
 },
 "retired": {
  "classes": {
   "indigo-brand": {
    "use": "indigo",
    "since": "0.9.60",
    "removed": "0.13.0"
   },
   "indigo-brand-deep": {
    "use": "indigo-deep",
    "since": "0.9.60",
    "removed": "0.13.0"
   }
  },
  "vars": {
   "--surface-page": {
    "aliases": "var(--paper)",
    "since": "0.10.0",
    "removed": "0.13.0"
   },
   "--surface-card": {
    "aliases": "var(--paper-warm)",
    "since": "0.10.0",
    "removed": "0.13.0"
   },
   "--surface-well": {
    "aliases": "var(--paper-deep)",
    "since": "0.10.0",
    "removed": "0.13.0"
   },
   "--text-strong": {
    "aliases": "var(--ink)",
    "since": "0.10.0",
    "removed": "0.13.0"
   },
   "--text-body": {
    "aliases": "var(--ink-soft)",
    "since": "0.10.0",
    "removed": "0.13.0"
   },
   "--text-muted-color": {
    "aliases": "var(--ink-muted)",
    "since": "0.10.0",
    "removed": "0.13.0"
   },
   "--text-on-ink": {
    "aliases": "var(--paper)",
    "since": "0.10.0",
    "removed": "0.13.0"
   },
   "--border-card": {
    "aliases": "var(--line-soft)",
    "since": "0.10.0",
    "removed": "0.13.0"
   },
   "--border-field": {
    "aliases": "var(--line-control)",
    "since": "0.10.0",
    "removed": "0.13.0"
   },
   "--border-divider": {
    "aliases": "var(--line-faint)",
    "since": "0.10.0",
    "removed": "0.13.0"
   },
   "--danger": {
    "aliases": "var(--terracotta-deep)",
    "since": "0.10.0",
    "removed": "0.13.0"
   }
  }
 },
 "roles": {
  "background": "The page ground and full-width sections; the cut-out fill of a control sitting on another surface (outline…",
  "foreground": "Strong text: headings, names, values, totals.",
  "card": "Raised surfaces in the page: cards, inline banners, a chat window, kanban tasks, an empty-state panel.",
  "card-foreground": "The default text colour inside a card, set once on its root.",
  "popover": "Anything that floats above the page: menus, selects, popovers, hover cards, dialogs, sheets, the command…",
  "popover-foreground": "The default text colour inside a floating layer, set once on its root.",
  "primary": "The main action and \"on / done\" states: default button, checked checkbox, radio and switch, progress fill,…",
  "primary-foreground": "Text and icons on an ink (`primary`) fill.",
  "secondary": "The fill of the secondary button and the neutral badge.",
  "secondary-foreground": "The label on a secondary button or badge.",
  "muted": "Quiet fills: icon wells, avatar fallbacks, skeletons, tab tracks.",
  "muted-foreground": "Supporting text: descriptions, captions, timestamps, helper text, placeholders, table meta.",
  "accent": "The highlighted item in a list or menu: the row under the pointer or keyboard focus, and the current item…",
  "accent-foreground": "Text and icons on a highlighted (`accent`) row.",
  "destructive": "Errors and destructive actions: the invalid-field border and ring, error text, the destructive button,…",
  "border": "Hairlines: the outline of a list, table or Calendar wrapper, a dashed dropzone, row rules, separators,…",
  "input": "The boundary of anything you type into or toggle (input, select, checkbox, radio, dropzone) and the empty…",
  "ring": "Keyboard focus, built into every primitive (3px at 50%).",
  "chart-1": "The first data series in a chart, passed as `var(--chart-1)` in the chart config.",
  "chart-2": "The second data series.",
  "chart-3": "The third data series.",
  "chart-4": "The fourth data series.",
  "chart-5": "The fifth data series.",
  "sidebar": "The ground of the app's side navigation rail.",
  "sidebar-foreground": "Default text and icons inside the sidebar; at 70% for group labels.",
  "sidebar-primary": "A solid ink element inside the sidebar, such as the workspace logo tile.",
  "sidebar-primary-foreground": "Text or an icon on a `sidebar-primary` fill.",
  "sidebar-accent": "The hovered, pressed and current item in the sidebar.",
  "sidebar-accent-foreground": "Text and icons on a highlighted sidebar item.",
  "sidebar-border": "Dividers and sub-menu guide lines inside the sidebar, and the outline of a floating sidebar.",
  "sidebar-ring": "The keyboard focus ring on sidebar items.",
  "text-accent-color": "The one italic accent word in a headline, and the colour of a bare `<a>`.",
  "link": "A text link inside prose, when you set its colour by hand (`text-link`).",
  "success": "Text or an icon confirming that something worked (`text-success`).",
  "warning": "Cautionary text or an icon (`text-warning`).",
  "info": "Neutral, informational text or an icon (`text-info`).",
  "working": "Live activity: an agent or job running right now (`text-working`).",
  "queued": "Waiting its turn in a run list (`text-queued`)."
 },
 "palette": {
  "bg": {
   "white": [
    "background",
    "card"
   ],
   "black": [
    "foreground"
   ],
   "grey": [
    "muted",
    "secondary"
   ],
   "red": [
    "destructive"
   ],
   "green": [
    "moss"
   ],
   "blue": [
    "indigo",
    "info"
   ],
   "yellow": [
    "gold",
    "warning"
   ],
   "purple": []
  },
  "text": {
   "white": [
    "primary-foreground",
    "card"
   ],
   "black": [
    "foreground"
   ],
   "grey": [
    "muted-foreground",
    "foreground"
   ],
   "red": [
    "destructive"
   ],
   "green": [
    "success"
   ],
   "blue": [
    "info",
    "link"
   ],
   "yellow": [
    "warning"
   ],
   "purple": []
  },
  "border": {
   "white": [
    "border"
   ],
   "black": [
    "foreground"
   ],
   "grey": [
    "border",
    "input",
    "ring"
   ],
   "red": [
    "destructive"
   ],
   "green": [
    "moss"
   ],
   "blue": [
    "indigo"
   ],
   "yellow": [
    "gold"
   ],
   "purple": []
  }
 },
 "swatches": {
  "background": "#F5EDDD",
  "foreground": "#2A2622",
  "card": "#EFE4CE",
  "card-foreground": "#2A2622",
  "popover": "#EFE4CE",
  "popover-foreground": "#2A2622",
  "primary": "#2A2622",
  "primary-foreground": "#F5EDDD",
  "secondary": "#E8DCC0",
  "secondary-foreground": "#2A2622",
  "muted": "#E8DCC0",
  "muted-foreground": "#675F58",
  "accent": "#E8DCC0",
  "accent-foreground": "#2A2622",
  "destructive": "#8A4530",
  "input": "#8A7F6E",
  "ring": "#4C5936",
  "chart-1": "#732510",
  "chart-2": "#345799",
  "chart-3": "#9D7614",
  "chart-4": "#79376C",
  "chart-5": "#4F6D1A",
  "sidebar": "#EFE4CE",
  "sidebar-foreground": "#2A2622",
  "sidebar-primary": "#2A2622",
  "sidebar-primary-foreground": "#F5EDDD",
  "sidebar-accent": "#E8DCC0",
  "sidebar-accent-foreground": "#2A2622",
  "sidebar-ring": "#4C5936",
  "link": "#4C5936",
  "success": "#4C5936",
  "warning": "#68522D",
  "info": "#44516D",
  "working": "#2F6B64",
  "queued": "#675F58",
  "paper": "#F5EDDD",
  "paper-warm": "#EFE4CE",
  "paper-deep": "#E8DCC0",
  "ink": "#2A2622",
  "ink-soft": "#5C524A",
  "ink-muted": "#675F58",
  "terracotta": "#C4684B",
  "terracotta-deep": "#8A4530",
  "moss": "#7A8C5C",
  "moss-deep": "#4C5936",
  "indigo": "#5B6B8A",
  "indigo-deep": "#44516D",
  "gold": "#B89968",
  "gold-deep": "#9A7D4E",
  "gold-text": "#68522D",
  "teal": "#4E938B",
  "teal-deep": "#2F6B64",
  "accent-pigment-text": "#4C5936"
 }
}

// ------------------------------------------------------------------ files
const SKIP_DIRS = new Set(['node_modules', '.next', 'dist', 'build', 'out', 'storybook-static', 'public', '.git', 'coverage', '.figma-type-audit'])
const EXTS = new Set(['.tsx', '.jsx', '.ts', '.js', '.mdx', '.html'])
// Never scan the check itself (its fix strings look like classes).
const SELF = /(^|[\\/])quill-check(\.template)?\.mjs$/

export function listFiles(root, { dirs = [root], includeUi = false } = {}) {
  const out = []
  const walk = (dir) => {
    for (const name of readdirSync(dir).sort()) {
      const p = join(dir, name)
      if (statSync(p).isDirectory()) {
        if (SKIP_DIRS.has(name)) continue
        // Stock shadcn primitives are restyled by tokens and never edited — not the agent's code.
        if (!includeUi && name === 'ui' && /(^|[\\/])components$/.test(dir)) continue
        walk(p)
      } else if (EXTS.has(extname(name)) && !name.endsWith('.d.ts') && !SELF.test(p)) out.push(p)
    }
  }
  for (const d of dirs) if (existsSync(d)) walk(d)
  return out
}

// ------------------------------------------------------------------ candidates
const PREFIX_SET = new Set(DATA.prefixes)
const QUILL = new Set(DATA.quillClasses)

// The utility after its variants: the segment after the last `:` that sits outside brackets,
// so `data-[state=open]:bg-x` and `has-[[aria-invalid=true]]:border-x` split correctly.
export function baseOf(token) {
  let depth = 0
  let cut = -1
  for (let i = 0; i < token.length; i++) {
    const ch = token[i]
    if (ch === '[' || ch === '(') depth++
    else if (ch === ']' || ch === ')') depth--
    else if (ch === ':' && depth === 0) cut = i
  }
  return token.slice(cut + 1).replace(/^!/, '').replace(/^-(?=[a-z])/, '')
}

// A utility we read is `prefix-something`: a bare word (`text`, `from`) is prose, not a class.
// Bracket utilities of every prefix pass too: layout ones are counted in the summary.
const looksLikeUtility = (base) => {
  const m = base.match(/^([a-z]+)-[a-z0-9([]/)
  return !!m && (PREFIX_SET.has(m[1]) || QUILL.has(base) || /-\[.+\]$/.test(base))
}

// Every whitespace-separated token inside a string literal that looks like a utility we read.
// Template-literal holes become spaces so `${cond ? 'a' : 'b'}` never glues onto a class.
export function extractCandidates(text) {
  const out = []
  const lineStarts = [0]
  for (let i = 0; i < text.length; i++) if (text[i] === '\n') lineStarts.push(i + 1)
  const lineOf = (idx) => {
    let lo = 0
    let hi = lineStarts.length - 1
    while (lo < hi) {
      const mid = (lo + hi + 1) >> 1
      if (lineStarts[mid] <= idx) lo = mid
      else hi = mid - 1
    }
    return lo
  }
  for (const m of text.matchAll(/'([^'\n]*)'|"([^"\n]*)"|`([^`]*)`/g)) {
    const literal = (m[1] ?? m[2] ?? m[3]).replace(/\$\{[^}]*\}/g, (h) => ' '.repeat(h.length))
    const start = m.index + 1
    for (const t of literal.matchAll(/\S+/g)) {
      // prose punctuation glued to a class (`font-heading,`) is not part of it
      const token = t[0].replace(/[.,;:!?'"]+$/, '')
      if (!token) continue
      const base = baseOf(token)
      if (!looksLikeUtility(base)) continue
      const idx = start + t.index
      const line = lineOf(idx)
      out.push({ token, base, line: line + 1, col: idx - lineStarts[line] + 1 })
    }
  }
  return out
}

// ------------------------------------------------------------------ rules 2–5 (pure)
const COLOR_PREFIXES = new Set(['bg', 'text', 'border', 'ring', 'outline', 'fill', 'stroke', 'from', 'to', 'via', 'decoration', 'divide', 'placeholder', 'caret', 'accent', 'shadow'])
const HUE_GROUP = { white: 'white', black: 'black', slate: 'grey', gray: 'grey', zinc: 'grey', neutral: 'grey', stone: 'grey', red: 'red', rose: 'red', orange: 'yellow', amber: 'yellow', yellow: 'yellow', lime: 'green', green: 'green', emerald: 'green', teal: 'blue', cyan: 'blue', sky: 'blue', blue: 'blue', indigo: 'blue', violet: 'purple', purple: 'purple', fuchsia: 'purple', pink: 'purple' }
const STOCK_SHADE = /^([a-z]+)-(50|[1-9]00|950)$/
const family = (prefix) => (['text', 'placeholder', 'caret', 'decoration', 'fill', 'stroke'].includes(prefix) ? 'text' : ['border', 'ring', 'outline', 'divide'].includes(prefix) ? 'border' : 'bg')
const withIntent = (prefix, role) => `${prefix}-${role}${DATA.roles[role] ? ` (${DATA.roles[role]})` : ''}`

// Rule 2: Tailwind's stock palette. Bare `indigo`, `teal`, `moss`… are Quill pigments and pass;
// only `white`, `black` and numbered shades are stock.
export function paletteRule(base) {
  const m = base.match(/^([a-z]+)-(.+?)(\/\d{1,3})?$/)
  if (!m) return null
  const [, prefix, rest] = m
  if (prefix === 'font' && rest === 'serif') return { rule: 'palette', fix: '→ font-heading (Fraunces, the display face)' }
  if (!COLOR_PREFIXES.has(prefix)) return null
  let hue = null
  if (rest === 'white' || rest === 'black') hue = rest
  else {
    const s = rest.match(STOCK_SHADE)
    if (s && HUE_GROUP[s[1]]) hue = s[1]
  }
  if (!hue) return null
  const roles = DATA.palette[family(prefix)][HUE_GROUP[hue]] ?? []
  const fix = roles.length
    ? `→ ${roles.map((r) => withIntent(prefix, r)).join(' or ')}`
    : '→ no Quill pigment sits here — pick a role by job (roles section of .claude/rules/quill.md)'
  return { rule: 'palette', fix }
}

const LAYOUT = new Set(['w', 'h', 'min', 'max', 'size', 'grid', 'inset', 'top', 'left', 'right', 'bottom', 'start', 'end', 'translate', 'p', 'px', 'py', 'pt', 'pr', 'pb', 'pl', 'ps', 'pe', 'm', 'mx', 'my', 'mt', 'mr', 'mb', 'ml', 'ms', 'me', 'gap', 'space', 'basis', 'col', 'row', 'aspect', 'z', 'order', 'flex', 'scroll', 'indent', 'columns', 'auto', 'content', 'origin', 'rotate', 'scale', 'skew', 'perspective', 'mask', 'clip', 'object', 'line', 'list', 'transition', 'delay', 'animate', 'will', 'backdrop', 'blur', 'brightness', 'contrast', 'opacity'])
const toPx = (v) => {
  const m = v.match(/^(-?[\d.]+)(px|rem|em)?$/)
  if (!m) return null
  const n = parseFloat(m[1])
  return m[2] === 'rem' || m[2] === 'em' ? n * 16 : n
}
const nearest = (table, n) => Object.entries(table).sort((a, b) => Math.abs(a[1] - n) - Math.abs(b[1] - n))[0]
const scale = (util, table, unit) => Object.entries(table).map(([k, v]) => `${util}-${k} ${v}${unit}`).join(' · ')
const motionFix = (kind) => kind === 'duration'
  ? `→ ${Object.entries(DATA.tokens.motion.duration).map(([v, n]) => `duration-(${v}) ${n}ms`).join(' · ')}`
  : `→ ${DATA.tokens.motion.ease.map((v) => `ease-(${v})`).join(' · ')}`

// Rule 4: a bracket value where Quill has a token. Returns a finding, 'layout' (counted), or
// null (not a bracket). Widths on border/ring/outline are layout: Tailwind's own scale, no token.
export function bracketRule(base) {
  const m = base.match(/^([a-z]+)((?:-[a-z]+)*)-\[(.+)\]$/)
  if (!m) return null
  const [, prefix, , inner] = m
  if (LAYOUT.has(prefix) || inner.startsWith('url(')) return 'layout'
  const colourLike = /^(#|rgba?\(|hsla?\(|oklch\(|oklab\()/.test(inner)
  const varRef = inner.match(/^var\((--[a-z0-9-]+)\)$/)
  if (COLOR_PREFIXES.has(prefix) && prefix !== 'text' && prefix !== 'shadow') {
    if (varRef) return DATA.vars[varRef[1]] ? { rule: 'bracket', fix: `→ ${prefix}-${DATA.vars[varRef[1]]}` } : 'layout'
    return colourLike ? { rule: 'bracket', fix: `→ a role or pigment — nearest ${hexHint(inner, prefix)}` } : 'layout'
  }
  if (prefix === 'text') {
    if (varRef) return DATA.vars[varRef[1]] ? { rule: 'bracket', fix: `→ text-${DATA.vars[varRef[1]]}` } : 'layout'
    if (colourLike) return { rule: 'bracket', fix: `→ a role or pigment — nearest ${hexHint(inner, 'text')}` }
    const n = toPx(inner)
    if (n === null) return 'layout'
    const [k, v] = nearest(DATA.tokens.text, n)
    return { rule: 'bracket', fix: Math.abs(v - n) < 0.05 ? `→ text-${k}` : `→ nearest text-${k} (${v}px); the scale: ${scale('text', DATA.tokens.text, 'px')}` }
  }
  if (prefix === 'rounded') {
    const n = toPx(inner)
    if (n === null) return { rule: 'bracket', fix: `→ one of ${scale('rounded', DATA.tokens.radius, 'px')}` }
    const [k, v] = nearest(DATA.tokens.radius, n)
    return { rule: 'bracket', fix: Math.abs(v - n) < 0.05 ? `→ rounded-${k}` : `→ nearest rounded-${k} (${v}px); the scale: ${scale('rounded', DATA.tokens.radius, 'px')}` }
  }
  if (prefix === 'tracking') {
    const n = parseFloat(inner)
    const [k, v] = nearest(DATA.tokens.tracking, n)
    return { rule: 'bracket', fix: Math.abs(v - n) < 0.005 ? `→ tracking-${k}` : `→ one of ${scale('tracking', DATA.tokens.tracking, 'em')}` }
  }
  if (prefix === 'leading') {
    const n = parseFloat(inner)
    const [k, v] = nearest(DATA.tokens.leading, n)
    return { rule: 'bracket', fix: Math.abs(v - n) < 0.005 ? `→ leading-${k}` : `→ one of ${scale('leading', DATA.tokens.leading, '')}` }
  }
  if (prefix === 'shadow') return { rule: 'bracket', fix: `→ one of ${DATA.tokens.shadow.map((s) => `shadow-${s}`).join(' · ')}` }
  if (prefix === 'font') return { rule: 'bracket', fix: inner.includes('family') ? '→ font-heading (Fraunces) or font-sans (Raleway) — the theme loads both' : '→ font-medium / font-semibold; Quill uses 400 / 500 / 600 only' }
  if (prefix === 'duration') return { rule: 'bracket', fix: motionFix('duration') }
  if (prefix === 'ease') return { rule: 'bracket', fix: motionFix('ease') }
  return 'layout'
}

// Rule 5 (classes): a retired Quill utility name. Longest name first so `indigo-brand-deep`
// is never reported as `indigo-brand`.
export function retiredRule(base) {
  for (const name of Object.keys(DATA.retired.classes).sort((a, b) => b.length - a.length)) {
    if (base.includes(name)) {
      const r = DATA.retired.classes[name]
      return { rule: 'retired', fix: `→ ${base.replace(name, r.use)} (renamed in ${r.since}; the old name compiles to nothing since ${r.removed})` }
    }
  }
  return null
}

// ------------------------------------------------------------------ raw colours + retired vars (whole text)
// A hex inside a bracket utility (bg-[#F5EDDD]) is rule 4's finding, not a second raw-colour one: `[` is in the lookbehind.
const HEX_RE = /(?<![\w&#[-])#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})(?![\w-])/g
const FN_RE = /\b(?:rgba?|hsla?|oklch|oklab)\([^)]*\)/g
const NOT_COLOUR_ATTR = /(?:href|to|id|htmlFor|key|name|aria-[a-z]+|data-[a-z-]+)=["'{`]?$/
const hex2rgb = (h) => {
  const s = h.length === 4 || h.length === 5 ? h.slice(1, 4).split('').map((c) => c + c).join('') : h.slice(1, 7)
  return [0, 2, 4].map((i) => parseInt(s.slice(i, i + 2), 16))
}
export function hexHint(value, prefix = 'bg') {
  if (!value.startsWith('#')) return Object.keys(DATA.swatches).slice(0, 4).map((r) => `${prefix}-${r}`).join(', ') + ', …'
  const [r, g, b] = hex2rgb(value)
  const near = Object.entries(DATA.swatches)
    .map(([name, hex]) => { const [x, y, z] = hex2rgb(hex); return [name, (x - r) ** 2 + (y - g) ** 2 + (z - b) ** 2] })
    .sort((a, b) => a[1] - b[1])
    .slice(0, 2)
  return near.map(([name]) => `${prefix}-${name} (${DATA.swatches[name]})`).join(' or ')
}

export function rawColourFindings(lines) {
  const out = []
  lines.forEach((text, i) => {
    for (const re of [HEX_RE, FN_RE]) {
      for (const m of text.matchAll(re)) {
        if (NOT_COLOUR_ATTR.test(text.slice(Math.max(0, m.index - 12), m.index))) continue
        out.push({ line: i + 1, col: m.index + 1, rule: 'raw-color', value: m[0], fix: `→ a role or pigment — nearest ${hexHint(m[0])}; a brand mark takes \`// quill-check: allow raw-color — <why>\` on the line above` })
      }
    }
    for (const m of text.matchAll(/var\((--[a-z0-9-]+)\)/g)) {
      const r = DATA.retired.vars[m[1]]
      if (r) out.push({ line: i + 1, col: m.index + 1, rule: 'retired', value: m[0], fix: `→ retired in ${r.since} and gone since ${r.removed}, so it resolves to nothing; it was ${r.aliases} — use the role that owns that value (roles section of .claude/rules/quill.md)` })
    }
  })
  return out
}

// ------------------------------------------------------------------ allows
// `quill-check: allow <rule> — <why>`. On the same line it covers that line; on a line of
// its own it covers the element that follows, up to the line that closes the tag — a JSX
// comment cannot sit between a tag's attributes, and an SVG brand mark's fill often does.
// The reason is mandatory: an allow without one is itself a finding, so exceptions never go quiet.
const ALLOW_RE = /quill-check:\s*allow\s+([a-z-]+)(?:\s*[—–-]+\s*(.*?))?\s*(?:\*\/|-->|\}|$)/
const ALLOW_ONLY_LINE = /^\s*(?:\{\/\*|\/\/|\/\*|<!--)\s*quill-check:/
export function allowsFor(lines, lineNo) {
  const found = []
  const same = lines[lineNo - 1]?.match(ALLOW_RE)
  if (same) found.push({ rule: same[1], reason: (same[2] ?? '').trim(), line: lineNo })
  for (let l = lineNo - 1; l >= 1 && l >= lineNo - 12; l--) {
    const text = lines[l - 1]
    if (ALLOW_ONLY_LINE.test(text)) { const m = text.match(ALLOW_RE); if (m) found.push({ rule: m[1], reason: (m[2] ?? '').trim(), line: l }); break }
    if (/>\s*$/.test(text) && l < lineNo - 1) break // a tag closed between: the allow above belongs to that element
  }
  return found
}

// ------------------------------------------------------------------ one file
export function scanFile(file, text) {
  const lines = text.split('\n')
  const findings = []
  let layout = 0
  for (const c of extractCandidates(text)) {
    const hit = retiredRule(c.base) ?? paletteRule(c.base)
    if (hit) { findings.push({ file, line: c.line, col: c.col, rule: hit.rule, value: c.token, fix: hit.fix }); continue }
    const b = bracketRule(c.base)
    if (b === 'layout') layout++
    else if (b) findings.push({ file, line: c.line, col: c.col, rule: b.rule, value: c.token, fix: b.fix })
  }
  for (const f of rawColourFindings(lines)) findings.push({ file, ...f })
  const seenAllow = new Set()
  for (const f of findings) {
    for (const a of allowsFor(lines, f.line)) {
      if (a.rule !== f.rule) continue
      if (a.reason) f.allowed = a.reason
      else if (!seenAllow.has(a.line)) {
        seenAllow.add(a.line)
        findings.push({ file, line: a.line, col: 1, rule: 'allow-without-reason', value: a.rule, fix: `→ write the reason after a dash: \`quill-check: allow ${a.rule} — why this one is right\`` })
      }
    }
  }
  return { findings, layout }
}

// ------------------------------------------------------------------ rule 1: ask the app's own Tailwind
// A Tailwind v4 utility exists only if the app's entry stylesheet defines its token. Compiling
// every candidate with the app's installed Tailwind is exact and needs no maintained list; a
// class that emits no CSS is dead in THIS app — a typo, or a theme that is not wired in.
const ENTRY_CANDIDATES = ['app/globals.css', 'src/app/globals.css', 'styles/globals.css', 'src/styles/globals.css']
const escapeClass = (s) => s.replace(/[^a-zA-Z0-9_-]/g, (ch) => '\\' + ch)

// A CSS package (tailwindcss, tw-animate-css, shadcn/tailwind.css) is not a JS module: its
// package.json points at the stylesheet through `exports[…].style`, `style` or a .css main, so
// Node's own resolver throws. Walk node_modules up from the importing file, then from cwd.
const findPackage = (name, from) => {
  let dir = from
  for (;;) {
    const p = join(dir, 'node_modules', name, 'package.json')
    if (existsSync(p)) return dirname(p)
    const up = dirname(dir)
    if (up === dir) return null
    dir = up
  }
}
export function resolveCssImport(id, base, cwd) {
  if (id.startsWith('.') || id.startsWith('/')) return resolve(base, id)
  const m = id.match(/^(@[^/]+\/[^/]+|[^/]+)(\/.*)?$/)
  const dir = findPackage(m[1], base) ?? findPackage(m[1], cwd)
  if (!dir) throw new Error('cannot find package ' + m[1] + ' from ' + base)
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'))
  const sub = m[2] ? '.' + m[2] : '.'
  const pick = (e) => (typeof e === 'string' ? e : e && typeof e === 'object' ? pick(e.style ?? e.default ?? e.import ?? Object.values(e)[0]) : null)
  let rel = pkg.exports ? pick(pkg.exports[sub] ?? (sub === '.' ? pkg.exports : null)) : null
  if (!rel && sub !== '.') rel = sub
  if (!rel) rel = pkg.style ?? (typeof pkg.main === 'string' && pkg.main.endsWith('.css') ? pkg.main : 'index.css')
  return join(dir, rel)
}

export async function resolveWithTailwind({ cwd, css, candidates }) {
  const entry = css
    ? resolve(cwd, css)
    : ENTRY_CANDIDATES.map((p) => join(cwd, p)).find((p) => existsSync(p) && /@import\s+["']tailwindcss["']/.test(readFileSync(p, 'utf8')))
  if (!entry || !existsSync(entry)) return { skipped: 'rule 1 skipped: no Tailwind entry found (a stylesheet with @import "tailwindcss") — run from the app root or pass --css <path>' }
  let tw
  let req
  try {
    req = createRequire(join(cwd, 'package.json'))
    // require.resolve lands on the CommonJS build, whose exports sit under `default`.
    const mod = await import(req.resolve('tailwindcss'))
    tw = typeof mod.compile === 'function' ? mod : mod.default
  } catch {
    return { skipped: 'rule 1 skipped: tailwindcss v4 not found from ' + cwd + ' — run from the app root' }
  }
  if (typeof tw.compile !== 'function') return { skipped: 'rule 1 skipped: tailwindcss v4 (compile API) is required' }
  const loadStylesheet = async (id, base) => {
    const p = resolveCssImport(id, base, cwd)
    return { base: dirname(p), content: readFileSync(p, 'utf8') }
  }
  const compiled = await tw.compile(readFileSync(entry, 'utf8'), { base: dirname(entry), loadStylesheet, loadModule: async () => ({ base: cwd, module: {} }) })
  const out = compiled.build([...candidates, 'dark:bg-background'])
  const unresolved = new Set([...candidates].filter((c) => !out.includes('.' + escapeClass(c))))
  // Tailwind keeps the LAST @custom-variant dark. shadcn init writes a stock one (.dark only);
  // if it sits below Quill's, dark: stops following data-theme while everything else works.
  const darkRule = out.match(/\.dark\\:bg-background[^{]*/)?.[0] ?? ''
  const darkFollowsThemes = darkRule.includes('[data-theme=')
  return { unresolved, entry, darkFollowsThemes }
}

const editDistance = (a, b) => {
  const d = Array.from({ length: a.length + 1 }, (_, i) => [i, ...Array(b.length).fill(0)])
  for (let j = 1; j <= b.length; j++) d[0][j] = j
  for (let i = 1; i <= a.length; i++) for (let j = 1; j <= b.length; j++) d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1))
  return d[a.length][b.length]
}

const NOT_WIRED = "→ Quill's theme is not wired into Tailwind here, so font-heading, the role classes and the status classes are all dead. Add `@import \"./quill-theme.css\"` to the stylesheet that holds `@import \"tailwindcss\"` (not to layout.tsx), or install with the CLI: npx shadcn@latest add @quill/quill"

// ------------------------------------------------------------------ run
export async function runCheck({ cwd = process.cwd(), dirs, includeUi = false, css, tailwind = true } = {}) {
  const files = listFiles(cwd, { dirs: dirs ?? [cwd], includeUi })
  const findings = []
  const notes = []
  let layout = 0
  const candidates = new Map() // token → [{ file, line, col }]
  for (const f of files) {
    const text = readFileSync(f, 'utf8')
    const rel = relative(cwd, f)
    const r = scanFile(rel, text)
    findings.push(...r.findings)
    layout += r.layout
    for (const c of extractCandidates(text)) (candidates.get(c.token) ?? candidates.set(c.token, []).get(c.token)).push({ file: rel, line: c.line, col: c.col })
  }
  if (tailwind) {
    const flagged = new Set(findings.map((f) => f.value))
    const r = await resolveWithTailwind({ cwd, css, candidates: [...candidates.keys()] })
    if (r.skipped) notes.push(r.skipped)
    else {
      // wired (bg-background resolves) but dark: ignores data-theme: the stock variant line won
      if (!r.unresolved.has('bg-background') && !r.darkFollowsThemes && candidates.has('bg-background')) {
        const entryText = readFileSync(r.entry, 'utf8').split('\n')
        const stock = entryText.findIndex((l) => /@custom-variant\s+dark\b/.test(l) && !l.includes('data-theme'))
        findings.push({ file: relative(cwd, r.entry), line: stock + 1 || 1, col: 1, rule: 'dark-variant', value: '@custom-variant dark', fix: "→ this stock line sits below Quill's and wins, so dark: fires only on .dark and never on data-theme: move the @import of quill-theme.css below it (or delete it — Quill's variant keeps .dark working)" })
      }
      const dead = [...r.unresolved].filter((t) => !flagged.has(t))
      // Three or more Quill classes dead at once is not three typos — the theme is missing.
      const notWired = dead.filter((t) => QUILL.has(baseOf(t))).length >= 3
      for (const t of dead) {
        const base = baseOf(t)
        let fix
        if (notWired && QUILL.has(base)) fix = NOT_WIRED
        else {
          const near = DATA.quillClasses.map((q) => [q, editDistance(base, q)]).filter(([, d]) => d <= 2).sort((a, b) => a[1] - b[1])[0]
          fix = near ? `→ no such utility — looks like a typo of ${near[0]}` : '→ no such utility in this app (it produces no CSS)'
        }
        for (const loc of candidates.get(t)) findings.push({ ...loc, rule: 'unresolved', value: t, fix })
      }
    }
  }
  findings.sort((a, b) => (a.file < b.file ? -1 : a.file > b.file ? 1 : a.line - b.line || a.col - b.col))
  return { findings, layout, notes }
}

// ------------------------------------------------------------------ output
const RULE_LABEL = { unresolved: 'unresolved', palette: 'palette', 'raw-color': 'raw colour', bracket: 'bracket', retired: 'retired', 'dark-variant': 'dark:', 'allow-without-reason': 'allow' }

export function formatText({ findings, layout, notes }, { quiet = false } = {}) {
  const lines = []
  const active = findings.filter((f) => !f.allowed)
  if (!quiet) {
    let current = null
    for (const f of findings) {
      if (f.file !== current) {
        current = f.file
        if (lines.length) lines.push('')
        lines.push(f.file)
      }
      lines.push(`  ${String(f.line).padStart(4)}  ${f.value.padEnd(28)}  ${RULE_LABEL[f.rule].padEnd(10)}  ${f.allowed ? `allowed — ${f.allowed}` : f.fix}`)
    }
    if (lines.length) lines.push('')
  }
  lines.push(`${active.length} finding${active.length === 1 ? '' : 's'} · ${findings.length - active.length} allowed · ${layout} layout size${layout === 1 ? '' : 's'} not checked`)
  for (const n of notes) lines.push(n)
  return lines.join('\n')
}

export async function main(argv = process.argv.slice(2)) {
  const opts = { dirs: [], includeUi: false, json: false, quiet: false, css: undefined }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === '--dir') opts.dirs.push(resolve(process.cwd(), argv[++i]))
    else if (a === '--css') opts.css = argv[++i]
    else if (a === '--include-ui') opts.includeUi = true
    else if (a === '--json') opts.json = true
    else if (a === '--quiet') opts.quiet = true
    else if (a === '--help' || a === '-h') {
      console.log(`quill-check ${DATA.version}\n  node scripts/quill-check.mjs [--dir <path>]... [--css <tailwind entry>] [--include-ui] [--json] [--quiet]\n  Lists every place the code stepped outside Quill, with the fix to write. Exit 1 when anything is found.`)
      return 0
    } else {
      console.error(`unknown option ${a} — try --help`)
      return 2
    }
  }
  const result = await runCheck({ cwd: process.cwd(), dirs: opts.dirs.length ? opts.dirs : undefined, includeUi: opts.includeUi, css: opts.css })
  const active = result.findings.filter((f) => !f.allowed).length
  if (opts.json) console.log(JSON.stringify({ version: DATA.version, summary: { findings: active, allowed: result.findings.length - active, layout: result.layout, notes: result.notes }, findings: result.findings }, null, 1))
  else console.log(formatText(result, { quiet: opts.quiet }))
  return active ? 1 : 0
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) process.exit(await main())
