import { icons } from '../components/ui/icons.core.mjs'

// The core set is generated by `npm run build:icons` from every icon name the
// blocks reference plus a curated common list. Deriving the list here keeps
// the usage page, the registry `docs` field and llms.txt identical to what the
// `icon` item actually ships — never hand-typed, so it cannot drift.
export const coreIconNames = Object.keys(icons).sort()

export const usage = {
  name: 'icon',
  kind: 'component',
  summary: `The Quill icon component — Material Symbols Outlined at weight 400, shipped as a self-contained core set of ${coreIconNames.length} names covering every icon the Quill blocks use.`,
  useWhen: [
    'You need a glyph inside a Quill block or beside text — a nav item, a status row, an inline affordance — and want it to match the outlined, weight-400 set every block already uses.',
  ],
  alternatives: [
    { name: 'button', when: 'the glyph is the whole control — use Button with an icon size (`icon`, `icon-sm`) and an `aria-label`; Icon on its own is never interactive.' },
    { name: 'spinner', when: 'the glyph means "loading" — Spinner carries the motion and the status semantics an icon does not.' },
  ],
  rules: [
    {
      id: 'core-names-only',
      do: `Pick a name from the core set the \`icon\` item ships (${coreIconNames.length} names): ${coreIconNames.join(', ')}.`,
      dont: 'Use any other Material Symbol name in an app. The consumer `<Icon>` bundles only the core set, so an unknown name renders as an empty, size-reserved box (plus a console warning in development); the design-system site lazy-loads the whole library, so a name can look fine on quilldesignsystem.com and be blank in your app.',
      visual: false,
    },
    {
      id: 'size-with-the-prop',
      do: 'Size through the `size` prop — a pixel number, or leave the `1em` default so the glyph follows the surrounding text.',
      dont: 'Scale an icon with a `transform` or a width/height class — the reserved box stops matching the glyph and the layout shifts.',
      visual: false,
    },
    {
      id: 'decorative-by-default',
      do: 'Leave an icon decorative (the default renders `aria-hidden`) when the text next to it already carries the meaning.',
      dont: 'Add an `aria-label` to an icon that sits beside its own label — screen readers then announce the meaning twice.',
      visual: false,
    },
  ],
  a11y: [
    'Without `aria-label` the SVG is `aria-hidden`; with one it becomes `role="img"` and is announced. Decorative next to text, labelled when the icon stands alone.',
    'Colour comes from `currentColor`, so an icon inherits the contrast of the text it sits in; carry status meaning in text or a ToneBadge, never in icon colour alone.',
  ],
  tokens: [],
}
