// One block per usage module, keyed by its exact import specifier. A wildcard
// (`declare module '*.usage.mjs'`) looks tempting but does not work here: with
// allowJs + moduleResolution "bundler", TS resolves these specifiers to the
// real .mjs files on disk, and wildcard ambient modules only apply when normal
// resolution fails. An exact-literal specifier match still augments the real
// module's inferred types, which is why this works. Generated by
// `npm run build:usage` from src/usage/index.mjs — do not hand-edit.

declare module '@/usage/activity-feed.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/alerts.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/analytics-charts.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/announcement-banner.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/badge-on-card.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/button.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/calendar-page.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/calendar-range.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/chat.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/checkout.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/combobox.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/command-palette.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/contact-form.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/cookie-consent.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/dashboard.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/data-table.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/dialog.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/empty-state.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/error-404.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/faq.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/feature-section.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/field.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/file-upload.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/footer.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/forgot-password.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/hero.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/input.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/input-group.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/input-otp.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/invoice.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/kanban.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/label.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/list-detail.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/login.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/login-minimal.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/login-oauth.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/login-split-panel.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/mail-shell.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/native-select.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/navbar.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/newsletter.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/notifications.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/onboarding.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/order-summary.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/otp-verification.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/page-header.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/pricing.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/profile-card.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/search-results.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/select.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/settings.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/sidebar-nav.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/signup.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/signup-social.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/stat-cards.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/stats-band.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/tabs-page.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/team-section.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/testimonial.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/textarea.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/theme-selector.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/wizard.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/render.mjs' {
  import type { Usage } from '@/usage/types'
  export function renderUsageDocs(usage: Usage): string
}
