// One block per usage module, keyed by its exact import specifier. A wildcard
// (`declare module '*.usage.mjs'`) looks tempting but does not work here: with
// allowJs + moduleResolution "bundler", TS resolves these specifiers to the
// real .mjs files on disk, and wildcard ambient modules only apply when normal
// resolution fails. An exact-literal specifier match still augments the real
// module's inferred types, which is why this works. Generated by
// `npm run build:usage` from src/usage/index.mjs — do not hand-edit.

declare module '@/usage/alerts.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/button.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/dialog.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/forgot-password.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/login.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/login-minimal.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/login-oauth.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/login-split-panel.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/otp-verification.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/signup.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/signup-social.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}

declare module '@/usage/render.mjs' {
  import type { Usage } from '@/usage/types'
  export function renderUsageDocs(usage: Usage): string
}
