/**
 * Generates the usage outputs derived from src/usage/*.usage.mjs:
 *   - public/usage/<name>.md            one full usage page per entry
 *   - public/usage/<name>.json          the same guide as data, for tools: keeps
 *                                       the rule ids and `visual` flags the
 *                                       page drops
 *   - public/usage/index.json           the list of every guide (a site cannot
 *                                       be listed like a folder), each with a
 *                                       content hash of its JSON and `code: true`
 *                                       when its source is published below
 *   - public/code/<name>.json           the source of each stock primitive that
 *                                       has a guide but no registry item, as the
 *                                       site renders it (src/components/ui), so a
 *                                       tool can read its anatomy; apps still
 *                                       install these from shadcn, not from here
 *   - registry.json                     `docs` field (shadcn CLI prints it at
 *                                       install time), `description`
 *                                       (:= summary), `meta.use_when`
 *                                       (:= useWhen[0]), `meta.not_for` (:= the
 *                                       alternatives, "when → name") and `categories`
 *                                       (:= meta.intent) for documented items.
 *                                       The base `quill` item has no usage
 *                                       module: its docs come from
 *                                       src/usage/theme-docs.mjs.
 * The usage module is the single source; `scripts/build-usage.test.mjs` fails
 * CI when a committed output is stale. Run `npm run build:usage` after
 * touching any usage file.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

import { ALL_USAGE } from '../src/usage/index.mjs'
import { renderUsageDocs, renderNotFor } from '../src/usage/render.mjs'
import { renderThemeDocs } from '../src/usage/theme-docs.mjs'
import { EXAMPLES, renderExampleDocs } from '../src/usage/examples.mjs'
import { isMain } from './lib/is-main.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
export const USAGE_DIR = join(root, 'public/usage')
export const REGISTRY_PATH = join(root, 'registry.json')
export const MODULES_DTS_PATH = join(root, 'src/usage/modules.d.ts')
export const CODE_DIR = join(root, 'public/code')
const UI_DIR = join(root, 'src/components/ui')

export function renderUsagePage(u) {
  return `# ${u.name} (${u.kind})\n\n${renderUsageDocs(u, { format: 'markdown' })}\n`
}

export function renderUsageJson(u) {
  return JSON.stringify(u, null, 2) + '\n'
}

/** A guide's fingerprint: the SHA-256 of its published JSON, so a tool can tell one guide changed. */
export function usageHash(u) {
  return createHash('sha256').update(renderUsageJson(u)).digest('hex')
}

/**
 * Guides whose source is published under /code: stock primitives Quill restyles but does not
 * ship (no registry item), read from the site's copy in src/components/ui.
 */
export function codeNames(all = ALL_USAGE, registry = JSON.parse(readFileSync(REGISTRY_PATH, 'utf8'))) {
  const shipped = new Set(registry.items.map((item) => item.name))
  return all.map((u) => u.name).filter((name) => !shipped.has(name) && existsSync(join(UI_DIR, `${name}.tsx`)))
}

export function renderCode(name) {
  const path = `components/ui/${name}.tsx`
  return JSON.stringify({ name, files: [{ path, content: readFileSync(join(UI_DIR, `${name}.tsx`), 'utf8') }] }, null, 2) + '\n'
}

export function renderUsageIndex(all = ALL_USAGE, withCode = new Set(codeNames(all))) {
  const guides = all.map((u) => ({
    name: u.name,
    kind: u.kind,
    summary: u.summary,
    hash: usageHash(u),
    ...(withCode.has(u.name) ? { code: true } : {}),
  }))
  return JSON.stringify({ schemaVersion: 1, guides }, null, 2) + '\n'
}

export function renderModulesDts(all = ALL_USAGE) {
  const header = `// One block per usage module, keyed by its exact import specifier. A wildcard
// (\`declare module '*.usage.mjs'\`) looks tempting but does not work here: with
// allowJs + moduleResolution "bundler", TS resolves these specifiers to the
// real .mjs files on disk, and wildcard ambient modules only apply when normal
// resolution fails. An exact-literal specifier match still augments the real
// module's inferred types, which is why this works. Generated by
// \`npm run build:usage\` from src/usage/index.mjs — do not hand-edit.`
  const usageBlocks = all.map(
    (u) => `declare module '@/usage/${u.name}.usage.mjs' {
  import type { Usage } from '@/usage/types'
  export const usage: Usage
}`,
  )
  const renderBlock = `declare module '@/usage/render.mjs' {
  import type { Usage } from '@/usage/types'
  export function renderUsageDocs(usage: Usage, options?: { format?: 'mdx' | 'markdown' }): string
}`
  return [header, ...usageBlocks, renderBlock].join('\n\n') + '\n'
}

export function usageDocsField(u) {
  const rules = u.rules.map((r) => `Do: ${r.do} Don't: ${r.dont}`).join(' ')
  const alts = u.alternatives.map((a) => `Use ${a.name} when ${a.when}`).join(' ')
  return [u.summary, rules, alts].filter(Boolean).join(' ')
}

export function injectRegistryDocs(registry, all = ALL_USAGE) {
  const byName = new Map(all.map((u) => [u.name, u]))
  for (const item of registry.items) {
    // The base theme item has no usage module — its docs are the theming
    // contract, generated from the token source. This is the one item every app
    // installs, so it is the only place the CLI can hand an app the rules.
    if (item.name === 'quill') {
      item.docs = renderThemeDocs()
      continue
    }
    // Page compositions: every field an agent reads comes from src/usage/examples.mjs
    // (order, description, docs); the entry in registry.json only names the file.
    const example = EXAMPLES.find((e) => e.name === item.name)
    if (example) {
      const home = registry.homepage.replace(/\/$/, '')
      item.title = example.title
      item.description = example.description
      item.docs = renderExampleDocs(example)
      item.registryDependencies = example.blocks.map((b) => `${home}/r/${b}.json`)
      continue
    }
    const u = byName.get(item.name)
    if (!u) continue
    item.docs = usageDocsField(u)
    item.description = u.summary
    // `categories` is shadcn's own schema-level taxonomy and survives
    // `shadcn build`; `meta` does not survive the MCP, which strips it before
    // search. Same source, published through both so future tooling reading
    // schema fields finds the intent too.
    if (item.type === 'registry:block') {
      item.meta = { ...item.meta, use_when: u.useWhen[0], not_for: renderNotFor(u) }
      if (item.meta.intent?.length) item.categories = [...item.meta.intent]
    }
  }
  return registry
}

if (isMain(import.meta.url)) {
  mkdirSync(USAGE_DIR, { recursive: true })
  for (const u of ALL_USAGE) {
    writeFileSync(join(USAGE_DIR, `${u.name}.md`), renderUsagePage(u))
    writeFileSync(join(USAGE_DIR, `${u.name}.json`), renderUsageJson(u))
  }
  // regenerated whole, so a primitive that gains a registry item or loses its guide drops out
  rmSync(CODE_DIR, { recursive: true, force: true })
  mkdirSync(CODE_DIR, { recursive: true })
  const withCode = codeNames()
  for (const name of withCode) writeFileSync(join(CODE_DIR, `${name}.json`), renderCode(name))
  writeFileSync(join(USAGE_DIR, 'index.json'), renderUsageIndex(ALL_USAGE, new Set(withCode)))
  const registry = injectRegistryDocs(JSON.parse(readFileSync(REGISTRY_PATH, 'utf8')))
  // registry.json is committed without a trailing newline (verified with
  // `python3 -c "print(open('registry.json','rb').read().endswith(b'\\n'))"` → False);
  // no `+ '\n'` here, unlike the brief's assumed format, to keep the diff minimal.
  writeFileSync(REGISTRY_PATH, JSON.stringify(registry, null, 2))
  writeFileSync(MODULES_DTS_PATH, renderModulesDts())
  console.log(`wrote ${ALL_USAGE.length} usage pages, ${withCode.length} primitive sources, registry.json docs fields, and modules.d.ts`)
}
