'use client'

import * as React from 'react'
import { cn } from '@/lib/utils'
import { icons } from './icons.core.mjs'
import type { IconName } from './icons.generated'

// Icon delivery: sync core + lazy long-tail.
// - Core icons (usage-derived ∪ curated common) live in icons.core.mjs and are
//   imported synchronously → instant render, no flash / layout shift.
// - Every other name is a per-icon module (src/components/ui/icons/<name>.mjs,
//   generated by `npm run build:icons`, gitignored). It is dynamic-imported on
//   mount via `import(\`./icons/${name}.mjs\`)` — the bundler auto-code-splits it
//   into its own chunk, so the initial graph only carries <Icon> + the core map.
// A module-level cache means each lazy icon loads at most once per session.

type IconData = { viewBox: string; paths: string[] }

const coreIcons = icons as Record<string, IconData>
const lazyCache = new Map<string, IconData>()

function Icon({
  name,
  size = '1em',
  className,
  'aria-label': ariaLabel,
  ...props
}: React.SVGProps<SVGSVGElement> & { name: IconName; size?: number | string }) {
  const core = coreIcons[name]

  const [lazy, setLazy] = React.useState<{ name: string; data: IconData } | null>(
    () => {
      const cached = lazyCache.get(name)
      return cached ? { name, data: cached } : null
    }
  )
  const [error, setError] = React.useState<Error | null>(null)

  React.useEffect(() => {
    if (core) return
    const cached = lazyCache.get(name)
    if (cached) {
      setLazy({ name, data: cached })
      return
    }
    let active = true
    import(`./icons/${name}.mjs`)
      .then((mod) => {
        const data = mod.default as IconData
        lazyCache.set(name, data)
        if (active) setLazy({ name, data })
      })
      .catch((err: unknown) => {
        if (active) setError(new Error(`Unknown icon: ${String(name)}`, { cause: err }))
      })
    return () => {
      active = false
    }
  }, [name, core])

  // Surface unknown-icon failures loudly in dev; render nothing in prod.
  if (error && process.env.NODE_ENV !== 'production') throw error

  const data =
    core ?? (lazy && lazy.name === name ? lazy.data : lazyCache.get(name))

  // Not yet resolved → same-size reserved placeholder (no layout shift).
  const viewBox = data?.viewBox ?? '0 0 24 24'

  return (
    <svg
      data-slot="icon"
      viewBox={viewBox}
      width={size}
      height={size}
      fill="currentColor"
      role={ariaLabel ? 'img' : undefined}
      aria-label={ariaLabel}
      aria-hidden={ariaLabel ? undefined : true}
      className={cn('inline-block shrink-0', className)}
      {...props}
    >
      {data?.paths.map((d, i) => <path key={i} d={d} />)}
    </svg>
  )
}

export { Icon, type IconName }
